//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public System.Guid ReviewId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid VehicleId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime PushlishDate { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
