//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Bookings = new HashSet<Booking>();
            this.Reviews = new HashSet<Review>();
        }
    
        public System.Guid VehicleId { get; set; }
        public string VehicleName { get; set; }
        public string Content { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid BrandId { get; set; }
        public System.Guid VariantId { get; set; }
        public string ImageVehicle { get; set; }
        public int Year { get; set; }
        public string RegistrationNumber { get; set; }
        public decimal VehiclePrice { get; set; }
        public int CodeDistrict { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual User User { get; set; }
        public virtual VehicleBrand VehicleBrand { get; set; }
        public virtual VehicleVariant VehicleVariant { get; set; }
    }
}
